# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuf

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class ShortcutEntry:
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ShortcutEntry()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsShortcutEntry(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    # ShortcutEntry
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ShortcutEntry
    def HexId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(
                flatbuffers.number_types.Uint64Flags, o + self._tab.Pos
            )
        return 0

    # ShortcutEntry
    def PolyIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(
                flatbuffers.number_types.Uint16Flags,
                a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 2),
            )
        return 0

    # ShortcutEntry
    def PolyIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint16Flags, o)
        return 0

    # ShortcutEntry
    def PolyIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ShortcutEntry
    def PolyIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0


def ShortcutEntryStart(builder):
    builder.StartObject(2)


def Start(builder):
    ShortcutEntryStart(builder)


def ShortcutEntryAddHexId(builder, hexId):
    builder.PrependUint64Slot(0, hexId, 0)


def AddHexId(builder, hexId):
    ShortcutEntryAddHexId(builder, hexId)


def ShortcutEntryAddPolyIds(builder, polyIds):
    builder.PrependUOffsetTRelativeSlot(
        1, flatbuffers.number_types.UOffsetTFlags.py_type(polyIds), 0
    )


def AddPolyIds(builder, polyIds):
    ShortcutEntryAddPolyIds(builder, polyIds)


def ShortcutEntryStartPolyIdsVector(builder, numElems):
    return builder.StartVector(2, numElems, 2)


def StartPolyIdsVector(builder, numElems):
    return ShortcutEntryStartPolyIdsVector(builder, numElems)


def ShortcutEntryEnd(builder):
    return builder.EndObject()


def End(builder):
    return ShortcutEntryEnd(builder)
