version: 2
updates:
  - package-ecosystem: "pip"
    directory: "pyproject.toml"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
