"""The one-wheel invariant of the data release, across the files that implement it.

``publish_data.yml`` states in its own header that it does not re-validate the data,
because ``build.yml`` compiled and checked it on the update pull request. That holds
only while the pull request and the tag are looking at *one* wheel: two builds agreeing
is a property of the converter being deterministic, which was shown once on one machine
and is not what a release should rest on. So ``check_data_updates.yml`` builds the wheel
from the data it just compiled, uploads it, and records its run id in ``DATA_BUILD_RUN``.

That one artefact is read from two ends, by one action each.
``.github/actions/obtain-data-wheel`` wants the wheel, to publish it;
``.github/actions/obtain-data`` wants the dataset inside it, because the binaries are
not committed and PyPI serves only the *previous* release while an update is in flight.
Both are the same hand-off and both fail the same quiet way, so they are covered
together here.

Nothing here can be executed - these files run on GitHub and a data update happens a few
times a year - so what is asserted is the handful of agreements that would otherwise fail
silently. Each of the four below degrades into "everyone builds their own wheel again",
which is green everywhere, indistinguishable in a log, and undoes the whole hand-off:
a stamp under a different name is simply never found, an artefact under a different name
is a warning nobody reads, a stamp written after the commit reaches no tag, and a
publishing job without ``actions: read`` discovers it at tag-push time.
"""

import re

import pytest
import yaml

from scripts.configs import DATA_BUILD_RUN_FILE, PROJECT_ROOT
from tests.auxiliaries import ACTION_DIR, WORKFLOW_DIR

UPDATE_WORKFLOW = WORKFLOW_DIR / "check_data_updates.yml"
BUILD_WORKFLOW = WORKFLOW_DIR / "build.yml"
PUBLISH_DATA_WORKFLOW = WORKFLOW_DIR / "publish_data.yml"
BENCHMARK_WORKFLOW = WORKFLOW_DIR / "benchmark.yml"
OBTAIN_ACTION = ACTION_DIR / "obtain-data-wheel" / "action.yml"
OBTAIN_ACTION_REF = "./.github/actions/obtain-data-wheel"
OBTAIN_DATA_ACTION = ACTION_DIR / "obtain-data" / "action.yml"
OBTAIN_DATA_ACTION_REF = "./.github/actions/obtain-data"
UPDATE_SCRIPT = PROJECT_ROOT / "update_data.sh"

# Every workflow that reaches for the recorded run, through either action.
RECORDED_RUN_CONSUMERS = (BUILD_WORKFLOW, PUBLISH_DATA_WORKFLOW, BENCHMARK_WORKFLOW)

# the update job, which is where the data is compiled and the wheel built from it
UPDATE_JOB = "open_update_pr"
# the step whose commit has to carry the stamp to the tag
COMMIT_STEP = "Commit and push the update branch"

STAMP_NAME = DATA_BUILD_RUN_FILE.name
# the one command that produces the wheel; every occurrence outside the update job and
# the action's fallback is a second, unreconciled build
BUILD_COMMAND = "uv build -v --package timezonefinder-data --wheel"


def _workflow(path):
    # `on:` is parsed as the boolean True by YAML 1.1, which is what PyYAML implements
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def _steps(workflow: dict) -> list[dict]:
    return [step for job in workflow["jobs"].values() for step in job["steps"]]


def _action_script(path=OBTAIN_ACTION) -> str:
    action = _workflow(path)
    return "\n".join(str(step.get("run", "")) for step in action["runs"]["steps"])


def _step_names(workflow: dict, job: str) -> list[str]:
    return [step.get("name", "") for step in workflow["jobs"][job]["steps"]]


@pytest.mark.unit
def test_one_stamp_name_across_its_writer_its_reader_and_what_clears_it() -> None:
    """Three files name this file and none of them imports the others.

    A rename on any one side does not fail: the reader finds no stamp, falls back to
    building, and every log looks exactly as it does when the data was regenerated by
    hand. ``scripts/configs.py`` holds the copy the tests read, so the assertion is that
    the shell-side spellings match it rather than each other.
    """
    for path in (UPDATE_WORKFLOW, OBTAIN_ACTION, OBTAIN_DATA_ACTION, UPDATE_SCRIPT):
        assert STAMP_NAME in path.read_text(encoding="utf-8"), (
            f"{path.name} does not name {STAMP_NAME}; the stamp is written, read and "
            "cleared in three separate files and nothing else ties them together"
        )


@pytest.mark.unit
def test_the_wheel_is_uploaded_under_the_name_the_action_downloads() -> None:
    """The upload and the download are the two halves of the hand-off.

    They live in different files and never meet, and a mismatch is not an error - the
    download simply finds nothing, the action warns, and both consumers build their own
    wheel again. That is the state this whole mechanism exists to leave.
    """
    uploads = [
        step
        for step in _workflow(UPDATE_WORKFLOW)["jobs"][UPDATE_JOB]["steps"]
        if str(step.get("uses", "")).startswith("actions/upload-artifact")
    ]
    assert len(uploads) == 1, "the update job must upload exactly one artefact"
    uploaded = uploads[0]["with"]["name"]

    for action in (OBTAIN_ACTION, OBTAIN_DATA_ACTION):
        assert f"artifact={uploaded}" in _action_script(action), (
            f"the update job uploads {uploaded!r}, which {action.parent.name} does "
            "not download"
        )


@pytest.mark.unit
def test_the_run_is_recorded_after_the_upload_and_before_the_commit() -> None:
    """Both orderings are load-bearing, and neither is enforced by anything else.

    The stamp claims "this run holds the wheel for this data". Written before the
    upload, it makes that claim about a run whose upload may still fail. Written after
    the commit, it never reaches the branch - so the tag carries no stamp and
    ``publish_data.yml`` rebuilds, which is precisely the outcome the decision refused.
    """
    names = _step_names(_workflow(UPDATE_WORKFLOW), UPDATE_JOB)
    recording = next(
        name for name in names if STAMP_NAME in name or "Record the run" in name
    )

    upload = next(
        i
        for i, step in enumerate(
            _workflow(UPDATE_WORKFLOW)["jobs"][UPDATE_JOB]["steps"]
        )
        if str(step.get("uses", "")).startswith("actions/upload-artifact")
    )
    assert upload < names.index(recording) < names.index(COMMIT_STEP)


def _recorded_run_callers() -> list[tuple[str, str, dict]]:
    """Every job that reaches for DATA_BUILD_RUN's artefact, through either action."""
    refs = {OBTAIN_ACTION_REF, OBTAIN_DATA_ACTION_REF}
    return [
        (path.name, name, job)
        for path in RECORDED_RUN_CONSUMERS
        for name, job in _workflow(path)["jobs"].items()
        if any(step.get("uses") in refs for step in job["steps"])
    ]


@pytest.mark.unit
def test_every_job_reaching_for_the_recorded_run_may_read_its_artefacts() -> None:
    """``actions: read`` is not implied, and its absence surfaces at the worst moment.

    Declaring any permission zeroes the rest, so a job that lists `id-token` and
    nothing else cannot read an artefact - and in ``publish_data.yml`` that is
    discovered on a tag push, with the release already half out.

    For the dataset side the failure is not even loud: ``obtain-data`` treats a failed
    download as "the recorded run has nothing" and fetches the published release
    instead, which on a data-update pull request is the release *before* the one under
    test. Everything then passes, against the wrong data.
    """
    callers = _recorded_run_callers()
    expected = {
        ("build.yml", "test"),
        ("build.yml", "make-data-wheel"),
        ("publish_data.yml", "publish-data-pypi"),
        ("benchmark.yml", "measure"),
    }
    assert {(path, job) for path, job, _ in callers} == expected, (
        f"the set of jobs reading the recorded run changed: {callers}"
    )

    for workflow_name, job_name, job in callers:
        permissions = job.get("permissions", {})
        assert permissions.get("actions") == "read", (
            f"{workflow_name}'s {job_name} uses the action without `actions: read`"
        )
        assert permissions.get("contents") == "read", (
            f"{workflow_name}'s {job_name} zeroes its checkout's `contents: read`"
        )


@pytest.mark.unit
def test_the_update_branch_stages_the_paths_it_names() -> None:
    """`git add -A` would make "no binaries are committed" .gitignore's property alone.

    The update job runs unattended and its pull request auto-merges, so a single file
    under the data directory escaping the ignore - a new subdirectory, a rule someone
    narrowed - would put ~62 MB into master with nobody in the loop. Staging by name
    means the job has to be changed on purpose for that to happen.
    """
    commit = next(
        step
        for step in _workflow(UPDATE_WORKFLOW)["jobs"][UPDATE_JOB]["steps"]
        if step.get("name") == COMMIT_STEP
    )
    script = str(commit["run"])
    for wildcard in ("git add -A", "git add --all", "git add ."):
        assert wildcard not in script, (
            f"the update job stages with {wildcard!r}; name the paths instead"
        )
    assert "packages/timezonefinder-data/pyproject.toml" in script, (
        "the data package's version bump is what a data release is; staging it by name "
        "is the point of the list"
    )


@pytest.mark.unit
def test_the_wheel_is_built_in_exactly_two_places() -> None:
    """One build for the release, one fallback - and no third that quietly reintroduces two.

    The refused option here was "the publish job regenerates", and it is one line to
    re-add. A second build looks identical in a log to the artefact path, so nothing
    downstream would report that the tag stopped publishing what CI validated.
    """
    builders = {
        path.name: [
            step.get("name", step.get("uses", ""))
            for step in _steps(_workflow(path))
            if BUILD_COMMAND in str(step.get("run", ""))
        ]
        for path in (UPDATE_WORKFLOW, BUILD_WORKFLOW, PUBLISH_DATA_WORKFLOW)
    }
    assert builders == {
        UPDATE_WORKFLOW.name: ["Build the data wheel"],
        BUILD_WORKFLOW.name: [],
        PUBLISH_DATA_WORKFLOW.name: [],
    }, f"the data wheel is built outside the update job: {builders}"

    assert len(re.findall(re.escape(BUILD_COMMAND), _action_script())) == 1
