"""Keep mypy's `ignore_errors` exemptions restricted to generated code.

`ignore_errors = true` silences *every* type error in the modules it names, so a
module on that list is one CI has stopped type-checking entirely - a blatant
`def f() -> int: return "x"` in it still reports "Success". That is invisible
from the outside: nothing fails, the hook stays green, and the module quietly
drifts out of the type system.

The list is meant to cover only `flatc`-generated bindings, which are not written
by hand and are regenerated by `make flatbuf`. This test exists because the
cheapest way to make a real type error go away is to append the offending module
here - which should be a deliberate, reviewed decision rather than a one-line
edit nobody notices.
"""

import re
import tomllib
from pathlib import Path
from typing import Any

import pytest
import yaml

from tests.auxiliaries import PROJECT_ROOT

PYPROJECT_PATH = PROJECT_ROOT / "pyproject.toml"
PRE_COMMIT_CONFIG_PATH = PROJECT_ROOT / ".pre-commit-config.yaml"

# Only modules inside a `generated` package may be exempted. Expressed as a rule
# rather than a literal allow-list so that regenerating or renaming bindings does
# not need a test edit, while a hand-written module still trips it.
GENERATED_PACKAGE_MARKER = "generated"


def _mypy_overrides(pyproject_path: Path) -> list[dict[str, Any]]:
    """Return the `[[tool.mypy.overrides]]` sections of pyproject.toml."""
    with open(pyproject_path, "rb") as f:
        pyproject = tomllib.load(f)
    return pyproject["tool"]["mypy"].get("overrides", [])


def _exempted_modules(pyproject_path: Path) -> list[str]:
    """Return every module pattern currently covered by `ignore_errors = true`."""
    return [
        module
        for override in _mypy_overrides(pyproject_path)
        if override.get("ignore_errors")
        for module in override["module"]
    ]


@pytest.mark.unit
def test_error_exemptions_cover_only_generated_code() -> None:
    hand_written = [
        module
        for module in _exempted_modules(PYPROJECT_PATH)
        if GENERATED_PACKAGE_MARKER not in module.split(".")
    ]
    assert not hand_written, (
        "mypy's `ignore_errors` list must only exempt generated bindings, but it "
        f"also silences all type errors in: {hand_written}. Fix the errors (or "
        "add a targeted `# type: ignore[code]` at the offending line) instead of "
        "turning type checking off for the whole module."
    )


@pytest.mark.unit
def test_generated_bindings_are_still_exempted() -> None:
    """The exemption that should exist is still in place.

    Guards the opposite mistake: dropping the generated-code entry would make
    `make hook` fail on `flatc` output nobody can reasonably fix by hand.
    """
    assert "timezonefinder.flatbuf.generated.*" in _exempted_modules(PYPROJECT_PATH)


@pytest.mark.unit
def test_scripts_are_type_checked_by_the_hook() -> None:
    """`scripts/` must stay outside the mypy hook's `exclude` pattern.

    The exclude is a second, quieter way to stop type-checking a directory: it
    takes no override entry and reports nothing, so the two tests above cannot
    see it. `scripts/` holds the data converter and the benchmark tooling, and
    while it was excluded its annotations drifted far enough to accumulate 15
    errors - a return type contradicted by the value returned, implicit
    `Optional` defaults, and `# type: ignore` codes mypy no longer emits.
    """
    hook_config = yaml.safe_load(PRE_COMMIT_CONFIG_PATH.read_text())
    excludes = [
        hook.get("exclude", "")
        for repo in hook_config["repos"]
        for hook in repo["hooks"]
        if hook["id"] == "mypy"
    ]
    assert excludes, "no mypy hook found in .pre-commit-config.yaml"
    offenders = [pattern for pattern in excludes if re.search(r"\bscripts\b", pattern)]
    assert not offenders, (
        "the mypy pre-commit hook excludes scripts/ again, which silently stops "
        f"type-checking the data converter and benchmark tooling: {offenders}"
    )
