name: GitHub Actions Version Updater

# Controls when the action will run.
on:
  schedule:
    # once a month
    - cron:  '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run GitHub Actions Version Updater
        uses: saadmk11/github-actions-version-updater@latest
        with:
          # [Required] Access token with `workflow` scope.
          token: ${{ secrets.GITHUB_TOKEN }}
